name = "CombinatorialGames"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CombinatorialGames"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "CombinatorialGames"
